### ISSUE TITLE
Typo in server.py

### ISSUE THREAD

**Issue by Fre011** [kit-colsoftdes/battleship_mp#14]
server.py, line 120:    `a_action["announce_shot"]`    should probably be    `b_action["announce_shot"] `.

https://github.com/kit-colsoftdes/battleship_mp/blob/dd1364338da16d789ac708f8c5513b557651c7b2/battleship_mp/server.py#L114-L121

**Comment by maxfischer2781** [comment]
Indeed this looks like a typo.
